// <auto-generated />
using System;
using System.Text.Json.Nodes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shellwright.Api.Data;

#nullable disable

namespace Shellwright.Api.Data.Migrations
{
    [DbContext(typeof(ShellwrightDbContext))]
    [Migration("20260902022512_CoreTenantModel")]
    partial class CoreTenantModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shellwright.Api.Domain.AppRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("BundleId")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)")
                        .HasColumnName("bundle_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentConfigVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_config_version_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_apps");

                    b.HasIndex("CurrentConfigVersionId")
                        .HasDatabaseName("ix_apps_current_config_version_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_apps_workspace_id");

                    b.HasIndex("WorkspaceId", "BundleId")
                        .IsUnique()
                        .HasDatabaseName("ix_apps_workspace_id_bundle_id");

                    b.ToTable("apps", (string)null);
                });

            modelBuilder.Entity("Shellwright.Api.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("OrgId", "Sha256")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_org_id_sha256");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Shellwright.Api.Domain.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<JsonObject>("Meta")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("subject_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_audit_events_actor_id");

                    b.HasIndex("OrgId", "At")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_events_org_id_at");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Shellwright.Api.Domain.ConfigVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("asset_key");

                    b.Property<JsonObject>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<string>("CodeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_key");

                    b.Property<string>("ContentKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("Id")
                        .HasName("pk_config_versions");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_config_versions_created_by");

                    b.HasIndex("AppId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_config_versions_app_id_created_at");

                    b.HasIndex("AppId", "CodeKey", "AssetKey", "ContentKey")
                        .IsUnique()
                        .HasDatabaseName("ix_config_versions_content_address");

                    b.ToTable("config_versions", (string)null);
                });

            modelBuilder.Entity("Shellwright.Api.Domain.Org", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("plan");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_orgs");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_orgs_slug")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("orgs", (string)null);
                });

            modelBuilder.Entity("Shellwright.Api.Domain.OrgMember", b =>
                {
                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("OrgId", "UserId")
                        .HasName("pk_org_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_org_members_user_id");

                    b.ToTable("org_members", (string)null);
                });

            modelBuilder.Entity("Shellwright.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Shellwright.Api.Domain.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("OrgId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_workspaces_org_id_slug");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("Shellwright.Api.Domain.AppRecord", b =>
                {
                    b.HasOne("Shellwright.Api.Domain.ConfigVersion", "CurrentConfigVersion")
                        .WithMany()
                        .HasForeignKey("CurrentConfigVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_apps_config_versions_current_config_version_id");

                    b.HasOne("Shellwright.Api.Domain.Workspace", "Workspace")
                        .WithMany("Apps")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_apps_workspaces_workspace_id");

                    b.Navigation("CurrentConfigVersion");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Shellwright.Api.Domain.Asset", b =>
                {
                    b.HasOne("Shellwright.Api.Domain.Org", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assets_orgs_org_id");
                });

            modelBuilder.Entity("Shellwright.Api.Domain.ConfigVersion", b =>
                {
                    b.HasOne("Shellwright.Api.Domain.AppRecord", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_config_versions_apps_app_id");

                    b.HasOne("Shellwright.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_config_versions_users_created_by");

                    b.Navigation("App");
                });

            modelBuilder.Entity("Shellwright.Api.Domain.OrgMember", b =>
                {
                    b.HasOne("Shellwright.Api.Domain.Org", "Org")
                        .WithMany("Members")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_members_orgs_org_id");

                    b.HasOne("Shellwright.Api.Domain.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_members_users_user_id");

                    b.Navigation("Org");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shellwright.Api.Domain.Workspace", b =>
                {
                    b.HasOne("Shellwright.Api.Domain.Org", "Org")
                        .WithMany("Workspaces")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_orgs_org_id");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("Shellwright.Api.Domain.Org", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("Shellwright.Api.Domain.User", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Shellwright.Api.Domain.Workspace", b =>
                {
                    b.Navigation("Apps");
                });
#pragma warning restore 612, 618
        }
    }
}
