using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Options;
using Shellwright.Api.Domain;
using Temporalio.Client;
using Temporalio.Exceptions;

namespace Shellwright.Api.Builds;

/// <summary>Where Temporal is.</summary>
public sealed class WorkflowOptions
{
    /// <summary>Configuration section these settings bind to.</summary>
    public const string SectionName = "Workflows";

    /// <summary>Temporal front-end address.</summary>
    [Required]
    public string Address { get; set; } = "localhost:7233";

    /// <summary>Temporal namespace.</summary>
    [Required]
    public string Namespace { get; set; } = "default";

    /// <summary>
    /// The task queue the orchestrator's workers poll.
    /// </summary>
    /// <remarks>
    /// ⚠️ Must match <c>BuildWorkflow.TaskQueue</c> in the orchestrator. A
    /// mismatch does not fail: the workflow is accepted and then sits in a
    /// queue nobody polls, so every build stays Queued forever and the only
    /// symptom is silence.
    /// </remarks>
    [Required]
    public string TaskQueue { get; set; } = "shellwright-builds";

    /// <summary>
    /// The workflow type name to start.
    /// </summary>
    /// <remarks>
    /// ⚠️ Started by name rather than by referencing the orchestrator's types.
    /// The two services deploy separately, and a project reference would make
    /// every orchestrator change a redeploy of the API — which is the coupling
    /// the duplicated enums and <c>BuildContractTests</c> exist to avoid.
    /// </remarks>
    [Required]
    public string WorkflowName { get; set; } = "BuildWorkflow";
}

/// <summary>
/// The argument the build workflow is started with.
/// </summary>
/// <remarks>
/// ⚠️ This record's field order and JSON shape are the wire contract with the
/// orchestrator's <c>BuildRequest</c>. It is declared here rather than shared
/// for the reason above; what keeps the two honest is that the enums inside it
/// are held equal by a test, and that the field names match.
/// </remarks>
/// <param name="BuildId">Identifier, generated by the API before the workflow starts.</param>
/// <param name="OrgId">Who is charged.</param>
/// <param name="AppId">The app being built.</param>
/// <param name="ConfigVersionId">The exact version to build. Never "the current one".</param>
/// <param name="Platform">Target platform.</param>
/// <param name="Type">Debug or release.</param>
public sealed record BuildWorkflowArgument(
    Guid BuildId,
    Guid OrgId,
    Guid AppId,
    Guid ConfigVersionId,
    BuildPlatform Platform,
    BuildType Type);

/// <summary>Starts and cancels build workflows in Temporal.</summary>
/// <param name="client">Connected Temporal client.</param>
/// <param name="options">Where Temporal is.</param>
public sealed class TemporalBuildWorkflowClient(
    ITemporalClient client,
    IOptions<WorkflowOptions> options) : IBuildWorkflowClient
{
    private readonly WorkflowOptions settings =
        options?.Value ?? throw new ArgumentNullException(nameof(options));

    /// <inheritdoc />
    public async Task StartAsync(Build build, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(build);

        var argument = new BuildWorkflowArgument(
            build.Id,
            build.OrgId,
            build.AppId,
            build.ConfigVersionId,
            build.Platform,
            build.Type);

        try
        {
            await client.StartWorkflowAsync(
                settings.WorkflowName,
                [argument],
                new Temporalio.Client.WorkflowOptions(build.WorkflowId, settings.TaskQueue));
        }
        catch (WorkflowAlreadyStartedException)
        {
            // ⚠️ Swallowed. The workflow id is derived from the build id, so
            // this means a retry of the same request reached Temporal twice —
            // and Temporal has already done exactly what was asked. Treating it
            // as a failure would report an error for a build that is running.
        }
    }

    /// <inheritdoc />
    public async Task CancelAsync(string workflowId, CancellationToken cancellationToken = default)
    {
        try
        {
            await client.GetWorkflowHandle(workflowId).CancelAsync();
        }
        catch (RpcException exception) when (exception.Code == RpcException.StatusCode.NotFound)
        {
            // ⚠️ Not an error either. A workflow whose history has been archived
            // is a build that already finished, and the endpoint has already
            // refused to cancel anything terminal — so reaching here means the
            // build finished between that check and this call.
        }
    }
}
