namespace Shellwright.Orchestrator.Workflows;

/// <summary>Which platform a build targets.</summary>
public enum BuildPlatform
{
    /// <summary>Android. Builds on Linux.</summary>
    Android = 0,

    /// <summary>iOS. Needs a macOS runner, which arrives in Sprint 08.</summary>
    Ios = 1,
}

/// <summary>What kind of artifact a build should produce.</summary>
public enum BuildType
{
    /// <summary>Unsigned, for inspection and for the emulator.</summary>
    Debug = 0,

    /// <summary>Shrunk and optimised, signed when credentials exist.</summary>
    Release = 1,
}

/// <summary>
/// Where a build has got to.
/// </summary>
/// <remarks>
/// ⚠️ The numeric values are not an ordering and nothing compares them. Builds
/// move between these by an explicit table in <c>BuildStateMachine</c>, because
/// "later than" is not a meaningful relation once <c>cancelled</c> exists.
/// </remarks>
public enum BuildState
{
    /// <summary>Accepted, waiting for a runner.</summary>
    Queued = 0,

    /// <summary>The generator is producing a project.</summary>
    Generating = 1,

    /// <summary>The toolchain is compiling it.</summary>
    Building = 2,

    /// <summary>Signature, manifest, size, and permissions are being checked.</summary>
    Verifying = 3,

    /// <summary>Finished, with an artifact.</summary>
    Succeeded = 4,

    /// <summary>Finished, without one.</summary>
    Failed = 5,

    /// <summary>Stopped on request.</summary>
    Cancelled = 6,
}

/// <summary>Why a build ended the way it did.</summary>
/// <param name="Code">Stable, documented code.</param>
/// <param name="Message">What a person can do about it.</param>
public sealed record BuildFailure(string Code, string Message);

/// <summary>Everything the workflow needs to run a build.</summary>
/// <param name="BuildId">Identifier, generated by the API before the workflow starts.</param>
/// <param name="OrgId">Tenant, for metering and for the runner's cache namespace.</param>
/// <param name="AppId">The app being built.</param>
/// <param name="ConfigVersionId">The exact version to build. Never "the current one".</param>
/// <param name="Platform">Target platform.</param>
/// <param name="Type">Debug or release.</param>
/// <remarks>
/// ⚠️ A version id, not a config document, and not "whatever is current".
///
/// Passing the document would put an unbounded blob into the workflow history,
/// which Temporal replays on every recovery. Passing "current" would mean a
/// build that is retried after a save produces a different artifact from the
/// one it was asked for — and the whole point of content-addressed versions is
/// that a build names exactly what it built.
/// </remarks>
public sealed record BuildRequest(
    Guid BuildId,
    Guid OrgId,
    Guid AppId,
    Guid ConfigVersionId,
    BuildPlatform Platform,
    BuildType Type);

/// <summary>How a build ended.</summary>
/// <param name="State">Terminal state.</param>
/// <param name="ArtifactReference">Content-addressed reference to the artifact, when there is one.</param>
/// <param name="CacheHit">Whether the artifact came from cache rather than a compiler.</param>
/// <param name="RunnerSeconds">Metered runner time. Zero on a cache hit, which is the point of caching.</param>
/// <param name="Failure">Why it failed, when it did.</param>
public sealed record BuildResult(
    BuildState State,
    string? ArtifactReference,
    bool CacheHit,
    int RunnerSeconds,
    BuildFailure? Failure)
{
    /// <summary>A build that never started because the configuration did not validate.</summary>
    /// <param name="detail">What is wrong with it.</param>
    /// <returns>The result.</returns>
    public static BuildResult Invalid(string detail) =>
        new(BuildState.Failed, null, false, 0, new BuildFailure("BLD_CONFIG_INVALID", detail));

    /// <summary>A build served entirely from cache.</summary>
    /// <param name="artifactReference">The cached artifact.</param>
    /// <returns>The result.</returns>
    public static BuildResult FromCache(string artifactReference) =>
        new(BuildState.Succeeded, artifactReference, true, 0, null);
}
